-- AlterTable
ALTER TABLE "Job" ADD COLUMN "dueDate" DATETIME;
ALTER TABLE "Job" ADD COLUMN "queuePosition" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Job" ADD COLUMN "qaChecklist" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Job" ADD COLUMN "qaPassed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Job" ADD COLUMN "reworkCost" REAL NOT NULL DEFAULT 0;
ALTER TABLE "Job" ADD COLUMN "reworkNotes" TEXT NOT NULL DEFAULT '';

-- CreateTable
CREATE TABLE "Supplier" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "contactEmail" TEXT NOT NULL DEFAULT '',
  "contactPhone" TEXT NOT NULL DEFAULT '',
  "notes" TEXT NOT NULL DEFAULT '',
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "MaterialPurchase" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "supplierId" TEXT NOT NULL,
  "materialName" TEXT NOT NULL,
  "quantityKg" REAL NOT NULL DEFAULT 0,
  "totalCost" REAL NOT NULL DEFAULT 0,
  "purchasedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "notes" TEXT NOT NULL DEFAULT '',
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "MaterialPurchase_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "Supplier" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);