name: Trigger auto deployment for workshoptrackv1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/workshoptrackv1-AutoDeployTrigger-f9170b35-ce95-46ca-8ac1-ad920e17b1fe.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo
      packages: write #Required to push images to GitHub Container Registry

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/backend
          file: ${{ github.workspace }}/backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/workshoptrackv1:${{ github.sha }},ghcr.io/${{ github.repository_owner }}/workshoptrackv1:latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.WORKSHOPTRACKV1_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WORKSHOPTRACKV1_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WORKSHOPTRACKV1_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: workshoptrackv1
          resourceGroup: ACA-WST
          imageToDeploy: ghcr.io/${{ github.repository_owner }}/workshoptrackv1:${{ github.sha }}
          registryUrl: ghcr.io
          registryUsername: ${{ github.actor }}
          registryPassword: ${{ secrets.GITHUB_TOKEN }}


